- name: Copy systemd service file
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Kafka service
  systemd:
    name: kafka
    enabled: yes
    state: started